<script setup lang="ts">
  import FileUpload from "primevue/fileupload"
  import { ref } from "vue"
  import { useRouter } from "vue-router"
  import PlaybookRepository from "../domain/PlaybookRepository"
  import Playbook from "../domain/Playbook"
  import { makePlaybookRepository } from "../provide"
  import NavigateToHome from "./NavigateToHome.vue"

  const chooseLabel = ref("Computer durchsuchen")
  const playbookRepository: PlaybookRepository = makePlaybookRepository()
  const router = useRouter()

  const upload = async (event: { files: File[] }) => {
    const playbookAsJson = await parsePlaybook(event)
    const playbook: Playbook = Playbook.fromJson(playbookAsJson)
    playbookRepository.save(playbook)
    await router.push("/mitra-frontend/contract")
  }

  const parsePlaybook = async (event: { files: File[] }) => {
    const file = event?.files[0]
    const reader = new FileReader()
    reader.readAsText(file)
    const result = await new Promise((resolve) => {
      reader.onload = () => {
        resolve(reader.result)
      }
    })
    return JSON.parse(result as string).playbook
  }
</script>

<template>
  <NavigateToHome />
  <section id="open-playbook">
    <h2 class="font-bold mb-4">Neuen Vertrag erstellen</h2>
    <label for="upload-playbook"
      >Wählen Sie ein Playbook von Ihrer Festplatte aus.
      <div class="mt-4">
        <FileUpload
          title="playbook-hochladen"
          :choose-label="chooseLabel"
          :show-upload-button="false"
          :show-cancel-button="false"
          :custom-upload="true"
          :auto="true"
          accept=".json"
          @uploader="upload"
        >
          <!-- This is a hack to overcome the pa11y and eslint errors arising from the fact the input element
          generated by FileUpload does not have a name or an id. Note that this additional input does not
           get rendered in the final HTML. -->
          <input id="upload-playbook" type="file" />

          <template #empty>
            <p>Datei in diesen Bereich ziehen.</p>
          </template>
        </FileUpload>
      </div>
    </label>
  </section>
</template>
