<script setup lang="ts">
  import FileUpload from "primevue/fileupload"
  import type { FileUploadUploaderEvent } from "primevue/fileupload"
  import { ref } from "vue"
  import { useRouter } from "vue-router"
  import { makeContractStore, makeFileSystemPlaybookLoader } from "../provide"
  import NavigateToHome from "./NavigateToHome.vue"
  import Contract from "../domain/Contract"

  const chooseLabel = ref("Computer durchsuchen")
  const playbookLoader = makeFileSystemPlaybookLoader()
  const contractStore = makeContractStore()
  const router = useRouter()

  const upload = async (event: FileUploadUploaderEvent) => {
    const file: File | File[] = event?.files
    const playbook = await playbookLoader.load(
      file instanceof Array ? file[0] : file
    )
    const contract: Contract = Contract.fromPlaybook(playbook)
    contractStore.save(contract.id, contract)
    await router.push("/mitra-frontend/contract/" + contract.id)
  }
</script>

<template>
  <NavigateToHome />
  <main id="open-playbook">
    <h2 class="font-bold mb-4">Neuen Vertrag erstellen</h2>
    <label for="upload-playbook"
      >Wählen Sie ein Playbook von Ihrer Festplatte aus.
      <div class="mt-4">
        <FileUpload
          title="playbook-hochladen"
          :choose-label="chooseLabel"
          :show-upload-button="false"
          :show-cancel-button="false"
          :custom-upload="true"
          :auto="true"
          accept=".json"
          @uploader="upload"
        >
          <!-- This is a hack to overcome the pa11y and eslint errors arising from the fact the input element
          generated by FileUpload does not have a name or an id. Note that this additional input does not
           get rendered in the final HTML. -->
          <input id="upload-playbook" type="file" />

          <template #empty>
            <p>Datei in diesen Bereich ziehen.</p>
          </template>
        </FileUpload>
      </div>
    </label>
  </main>
</template>
