<script setup lang="ts">
  import FileUpload from "primevue/fileupload"
  import { ref } from "vue"
  import { useRouter } from "vue-router"
  import { makeContractStore, makeFileSystemContractLoader } from "../provide"
  import NavigateToHome from "./NavigateToHome.vue"

  const chooseLabel = ref("Computer durchsuchen")
  const contractLoader = makeFileSystemContractLoader()
  const contractStore = makeContractStore()
  const router = useRouter()

  const upload = async (event: { files: File[] }) => {
    const file = event?.files[0]
    const contract = await contractLoader.load(file)
    console.log(contract)
    contractStore.save(contract.id, contract)
    await router.push("/mitra-frontend/contract/" + contract.id)
  }
</script>

<template>
  <NavigateToHome />
  <section id="open-contract">
    <h2 class="font-bold mb-4">Vertrag bearbeiten</h2>
    <label for="upload-contract"
      >Wählen Sie einen Vertrag von Ihrer Festplatte aus.
      <div class="mt-4">
        <FileUpload
          title="contract-hochladen"
          :choose-label="chooseLabel"
          :show-upload-button="false"
          :show-cancel-button="false"
          :custom-upload="true"
          :auto="true"
          accept=".json"
          @uploader="upload"
        >
          <!-- This is a hack to overcome the pa11y and eslint errors arising from the fact the input element
          generated by FileUpload does not have a name or an id. Note that this additional input does not
           get rendered in the final HTML. -->
          <input id="upload-contract" type="file" />

          <template #empty>
            <p>Datei in diesen Bereich ziehen.</p>
          </template>
        </FileUpload>
      </div>
    </label>
  </section>
</template>
